const MyProduct = [
  {
    id: "1",
    image: "./assets/profilePic.jpg",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    activity: "Published",
    demands: "orders",
    nameofProduct: "category cataplayer",
    moneyofclient: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numOfOrders: "5",
  },
  {
    id: "2",
    image: "./assets/profilePic.jpg",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    activity: "Published",
    demands: "orders",
    nameofProduct: "category cataplayer",
    moneyofclient: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numOfOrders: "5",
  },
  {
    id: "3",
    image: "./assets/profilePic.jpg",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    activity: "Published",
    demands: "orders",
    nameofProduct: "category cataplayer",
    moneyofclient: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numOfOrders: "5",
  },
  {
    id: "4",
    image: "./assets/profilePic.jpg",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    activity: "Published",
    demands: "orders",
    nameofProduct: "category cataplayer",
    moneyofclient: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numOfOrders: "5",
  },
  {
    id: "5",
    image: "./assets/profilePic.jpg",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    activity: "Published",
    demands: "orders",
    nameofProduct: "category cataplayer",
    moneyofclient: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numOfOrders: "5",
  },
  {
    id: "6",
    image: "./assets/profilePic.jpg",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    activity: "Published",
    demands: "orders",
    nameofProduct: "category cataplayer",
    moneyofclient: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numOfOrders: "5",
  },
];
export default MyProduct;
