const AllOrdersData = [
  {
    Id: "1",
    IdofOrder: "OrderID",
    customername: "Customer",
    kind: "Product",
    dateOfOrder: "Order date",
    salary: "amount",
    method: "Payment Method",
    state: "order state",
    orderid: "#AB10",
    name: "Johnny Depp",
    product: "Big diggying",
    date: "5.May.2022 11:30AM",
    money: "$1000",
    payment: "Visa",
    orderState: "Delivered",
  },
  {
    Id: "2",
    IdofOrder: "OrderID",
    customername: "Customer",
    kind: "Product",
    dateOfOrder: "Order date",
    salary: "amount",
    method: "Payment Method",
    state: "order state",
    orderid: "#AB10",
    name: "Johnny Depp",
    product: "Big diggying",
    date: "5.May.2022 11:30AM",
    money: "$1000",
    payment: "Visa",
    orderState: "Delivered",
  },
  {
    Id: "3",
    IdofOrder: "OrderID",
    customername: "Customer",
    kind: "Product",
    dateOfOrder: "Order date",
    salary: "amount",
    method: "Payment Method",
    state: "order state",
    orderid: "#AB10",
    name: "Johnny Depp",
    product: "Big diggying",
    date: "5.May.2022 11:30AM",
    money: "$1000",
    payment: "Visa",
    orderState: "Delivered",
  },
  {
    Id: "4",
    IdofOrder: "OrderID",
    customername: "Customer",
    kind: "Product",
    dateOfOrder: "Order date",
    salary: "amount",
    method: "Payment Method",
    state: "order state",
    orderid: "#AB10",
    name: "Johnny Depp",
    product: "Big diggying",
    date: "5.May.2022 11:30AM",
    money: "$1000",
    payment: "Visa",
    orderState: "Delivered",
  },
  {
    Id: "5",
    IdofOrder: "OrderID",
    customername: "Customer",
    kind: "Product",
    dateOfOrder: "Order date",
    salary: "amount",
    method: "Payment Method",
    state: "order state",
    orderid: "#AB10",
    name: "Johnny Depp",
    product: "Big diggying",
    date: "5.May.2022 11:30AM",
    money: "$1000",
    payment: "Visa",
    orderState: "Delivered",
  },
];
export default AllOrdersData;
