const productFilterData = [
  {
    id: "1",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    publish: "Published",
    order: "Orders",
    nameofPro: "category Cataplyer",
    amount: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numofOrders: "5",
  },
  {
    id: "2",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    publish: "Published",
    order: "Orders",
    nameofPro: "category Cataplyer",
    amount: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numofOrders: "5",
  },
  {
    id: "3",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    publish: "Published",
    order: "Orders",
    nameofPro: "category Cataplyer",
    amount: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numofOrders: "5",
  },
  {
    id: "4",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    publish: "Published",
    order: "Orders",
    nameofPro: "category Cataplyer",
    amount: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numofOrders: "5",
  },
  {
    id: "5",
    name: "Big digging",
    money: "Price",
    star: "Rating",
    publish: "Published",
    order: "Orders",
    nameofPro: "category Cataplyer",
    amount: "$1000",
    rate: "4.5",
    date: "5.May.2022 11:30AM",
    numofOrders: "5",
  },
];
export default productFilterData;
